# Generated by Django 4.1.3 on 2022-12-11 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
